version: '3.4'

x-common-variables: &common-variables
  MINESWEEPER_DATABASE: minesweeper
  
services:
 
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      <<: *common-variables
    volumes:
      - ./build:/docker-entrypoint-initdb.d/  
  minesweeper:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    links:
      - db:db
    ports:
      - '8080:8080'
    environment:
      GO_ENVIRONMENT: local
      <<: *common-variables
