version: '3.4'

x-common-variables: &common-variables
  MINESWEEPER_DATABASE: minesweeper
  
services:
 
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      <<: *common-variables
    volumes:
      - ./build:/docker-entrypoint-initdb.d/  
  minesweeper:
    #entrypoint: /go/src/github.com/jiseruk/minesweeper/cmd/minesweeper/wait-for-it.sh db:5432 --timeout=0 -- /go/src/github.com/jiseruk/minesweeper/cmd/minesweeper/main
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    links:
      - db:db
    ports:
      - '8080:8080'
    volumes:
      - ./:/go/src/github.com/jiseruk/minesweeper
    environment:
      GO_ENVIRONMENT: local
      <<: *common-variables
