FROM golang:latest as builder
RUN mkdir -p /go/src/github.com/jiseruk/minesweeper
WORKDIR /go/src/github.com/jiseruk/minesweeper
COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN go get github.com/githubnemo/CompileDaemon
WORKDIR /go/src/github.com/jiseruk/minesweeper/cmd/minesweeper
#ENTRYPOINT ["../../wait-for-it.sh", "db:5432", "--timeout=0", "--", "CompileDaemon", "--build='go build main.go'", "--command=./main"]
ENTRYPOINT ../../wait-for-it.sh db:5432 --timeout=0 -- CompileDaemon --build='go build main.go' --command=./main
#ENTRYPOINT ["/bin/bash"]
#CMD ["go", "run", "main.go"]
EXPOSE 8080 
